name: Deploy naar Hostnet

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repo uitchecken
        uses: actions/checkout@v4

      - name: Uploaden naar httpdocs via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: ./httpdocs/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
